### ISSUE TITLE
Crash report wpandroid: SQLiteException in TracksDatabaseHelper.getReadableDb

### ISSUE THREAD

**Issue by maxme** [Automattic/Automattic-Tracks-Android#24]
```
Fatal Exception: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/org.wordpress.android/databases/tracks.db' to 'en_AU'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:393)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:216)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:581)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:275)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.automattic.android.tracks.datasets.TracksDatabaseHelper.getDatabase(TracksDatabaseHelper.java:35)
       at com.automattic.android.tracks.datasets.TracksDatabaseHelper.getReadableDb(TracksDatabaseHelper.java:49)
       at com.automattic.android.tracks.datasets.EventTable.getEventsCount(EventTable.java:56)
       at com.automattic.android.tracks.TracksClient$2.run(TracksClient.java:137)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:369)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:216)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:581)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:275)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.automattic.android.tracks.datasets.TracksDatabaseHelper.getDatabase(TracksDatabaseHelper.java:35)
       at com.automattic.android.tracks.datasets.TracksDatabaseHelper.getReadableDb(TracksDatabaseHelper.java:49)
       at com.automattic.android.tracks.datasets.EventTable.getEventsCount(EventTable.java:56)
       at com.automattic.android.tracks.TracksClient$2.run(TracksClient.java:137)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by maxme** [comment]
Not sure we can fix this without forking `SQLiteOpenHelper`.
