### ISSUE TITLE
android.database.sqlite.SQLiteReadOnlyDatabaseException

### ISSUE THREAD

**Issue by jkmassel** [Automattic/Automattic-Tracks-Android#42]
From Fabric:

```
Fatal Exception: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
       at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
       at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
       at com.automattic.android.tracks.datasets.EventTable.insertEvent(EventTable.java:102)
       at com.automattic.android.tracks.TracksClient$1.run(TracksClient.java:117)
       at java.lang.Thread.run(Thread.java:761)
```

**Source:** 5c4ef231f8b88c2963cb9e91

**Comment by wzieba** [comment]
Probably related to #68
